#%RAML 1.0 DataType

type: object
properties:
  contactID: string
  externalID?: string
  typeID?: string
  isInactive?: boolean
  imageID?: string
  largeMemo?: string
  createDateTime?: number
  createEmployeeID?: string
  editDateTime?: number
  editEmployeeID?: string
  countryCode?: string
  state?: string
  city?: string
  postalCode?: string
  address1?: string
  address2?: string
  address3?: string
  address4?: string
  address5?: string
  fiscalCode?: string
  phone?: string
  mobilePhone?: string
  workPhone?: string
  fax?: string
  email1?: string
  email2?: string
  homePage?: string
  gender?: number
  birthDay?: number
  birthMonth?: number
  birthYear?: number
  title?: string
  firstName?: string
  lastName?: string
  middleName?: string
  organization?: string
  postition?: string
  customGuid1?: string
  customGuid2?: string
  customGuid3?: string
  customGuid4?: string
  customGuid5?: string
  customGuid6?: string
  customNumber1?: number
  customNumber2?: number
  customDecimal1?: string
  customDecimal2?: string
  customText1?: string
  customText2?: string
  customFlag1?: boolean
  customFlag2?: boolean
  customDate1?: number
  customDate2?: number
  customDate3?: number
  customDate4?: number
  customDate5?: number
  customDate6?: number
  customDate7?: number
  customDate8?: number