#%RAML 1.0 DataType

type: object
properties:
  addressID: string
  isDeleted?: boolean
  type?: string
  countryCode?: string
  state?: string
  address1?: string
  address2?: string
  address3?: string
  address4?: string
  address5?: string
  fiscalCode?: string
  city?: string
  postalCode?: string
  organization?: string
  title?: string
  firstName?: string
  middleName?: string
  lastName?: string
  suffix?: string
  phone?: string
  fax?: string
  email?: string
  VATRegistrationNumber?: string